Brush ups and requirements
elisa-tech/wg-medical-devices pull request #17
Opened 2023-08-13 08:53 UTC by milanlakhani

Added L1 and L2 requirement lists in yml.
Applied discussed changes to yml component files.

2023-08-31 13:29 UTC, kestewart requested changes
Can you separate this into 2 pull requests please.   
One for the scripts,  and one for the outcome of running the scripts.

Also,   all python scripts should have licensing information in the top of them

2023-08-31 13:29 UTC, kestewart commented on applying-stpa/gen_requirements.py
> +import yaml
Please add a license in SPDX format to the script.

2023-08-31 13:29 UTC, kestewart commented on applying-stpa/l2_reqs.txt
> + ('REQ-111', '(1) process topic: Data formats (APIs ?) that OpenAPS works with must be specified'),
Not sure about the syntax "(1)" process topic"  - should this be included in the requirements set?

2023-08-31 14:08 UTC, kestewart commented on applying-stpa/gen_requirements.py
> +import yaml
Put in a python comment something like...
''' SPDX-License-Identifier: GPL-2.0 '''

2023-08-31 14:09 UTC, kestewart commented on applying-stpa/l2_reqs.txt
> + ('REQ-36', "(I need help with this one!  It's not under OpenAPS's control)"),
Let's do a pass after separate commitment.

2023-08-31 14:12 UTC, kestewart commented on applying-stpa/requirements.txt
> +pandas
Add comment to explain why done.

2023-09-14 16:40 UTC, milanlakhani commented
> Can you separate this into 2 pull requests please. One for the scripts, and one for the outcome of running the scripts.
> 
> Also, all python scripts should have licensing information in the top of them

This is both done

2023-10-12 14:08 UTC, kestewart commented
DIscussed on call today, and Milan will make an additional split.

2023-10-12 15:37 UTC, milanlakhani commented
> DIscussed on call today, and Milan will make an additional split.

This should now be done

2023-11-02 14:00 UTC, kestewart approved these changes
Thanks Milan.  Looks good!

2023-11-02 14:01 UTC, kestewart commented
Hmm... can you add your Signed-off-by:  into this thread, if not in the commit.    Then I'll merge.

2023-11-09 15:45 UTC, Shefali199 approved these changes

2023-11-23 19:14 UTC, milanlakhani commented
Hi Kate, sorry for the delay, I've added sign offs to all my commits! I'll keep an eye on the CI. Also I am no longer to access the OpenAPS STPA spreadsheet, are you an owner who can change this? Otherwise it might be to do with the fact that originally this was linked to my Codethink address, I can e-mail CT about it.

2024-01-17 15:08 UTC, merged