WIP: Add requirements
elisa-tech/wg-medical-devices pull request #18
Opened 2023-09-14 16:38 UTC by milanlakhani

Add requirements for STPA levels 1 and 2

2023-11-09 15:16 UTC, kestewart requested changes
Requirements are starting to look a lot better, from the generated version, but there's stills some polishing needed.

We also need to make the way we refer to certain elements consistent - Raspbian OS, Raspi,  etc.

2023-11-09 15:16 UTC, kestewart commented on applying-stpa/l2_reqs.txt
> + ('REQ-38', '(should the fragment to the left be removed?)'),
Please fix this one up.

2023-11-09 15:16 UTC, kestewart commented on applying-stpa/l2_reqs.txt
> + ('REQ-124', 'There should be a notification when the OpenAPS app commands have been  updated'),
Notification to who/what?

2023-11-09 15:16 UTC, kestewart commented on applying-stpa/l2_reqs.txt
> + ('REQ-123', 'When an updated version of OpenAPS app is being used, the app commands in the OpenAPS algorithm should be refactored'),
What is being looked for in the "refactoring"

2023-11-09 15:16 UTC, kestewart commented on applying-stpa/l2_reqs.txt
> + ('REQ-118', 'process topic: correct specification and implementation of data processing must be verified'),
This doesn't look like a requirement.   rework?

2023-11-09 15:16 UTC, kestewart commented on applying-stpa/l2_reqs.txt
> + ('REQ-117', 'process topic: details of data processing must be specified to ensure the processing algorithms are suitable for the data formats, sizes and timing'),
This doesn't look like a requirement.   Rework?

2023-11-09 15:17 UTC, kestewart commented
@milanlakhani Please add your "Signed-off-by" to each of the pull requests.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-2', 'Raspberry OS is up to date'),
Rephrase to something like "Raspberry OS must be up to date" or as an assumption "Raspberry OS is assumed to be up to date", don't know what was meant here originally.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-12', 'There should be continuous testing of OpenAPS dependencies with updated OS'),
Does this mean online testing during runtime? Needs to be more specific (without the context from STPA)

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-13', 'When there are software updates on the RasPi, OpenAPS should stop making recommendations'),
Recommendations regarding what and to what/who

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-21', 'Need to know the version(s) of the dependencies that are in the RasPi OS that is compatible with the version number of OpenAPS that is trying to be installed'),
Who needs to know that? Or who needs to provide this information?

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-24', 'Need to know the version(s) of Raspbian OS that is compatible with the version number of OpenAPS that is trying to be installed'),
Who needs to know that and who needs to provide this information?

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-35', 'If RasPi OS forwards the data in the incorrect format, OpenAPS shall check to ensure that the data is in the correct format.  If RasPi OS does not forward the data, OpenAPS shall impleme
We might want to split this into separate requirements.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-36', "(I need help with this one!  It's not under OpenAPS's control)"),
We need to revisit the STPA to clearify this one.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-57', 'Register other device'),
We need to revisit the STPA to clearify this one.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-58', 'Ignore other device'),
We need to revisit the STPA to clearify this one.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-62', 'Place command in queue to resend later if not safety-critical'),
We need to revisit the STPA to clearify this one.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-64', 'Warn user and turn off if safety-critical'),
We need to revisit the STPA to clearify this one.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-66', 'Ignore command, warn user and wait for next command'),
We need to revisit the STPA to clearify this one.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-67', 'Request device resends command'),
We need to revisit the STPA to clearify this one.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-69', 'Ignore command/warn user'),
We need to revisit the STPA to clearify this one.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-70', 'Warn user and shut down'),
We need to revisit the STPA to clearify this one.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-76', "Use Raspbian OS that doesn't have that bug in it"),
That's a little bit vague. And impossible...

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-78', 'Include error-checking or redundancies in the command that will reduce the likelihood of interference causing a misinterpretation of the command'),
Which command?

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-80', 'Wait for acknowledge from NightScout; otherwise keep in queue and attempt to resend again'),
This needs more detail to be understandable without the context from STPA.

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-81', 'Use latest Raspbian OS?'),
This might interfere with the requirement to use a compatible version

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-88', 'Function in the algorithm must take less than X seconds to be applied to the RasPi OS'),
Do we need to specify X?

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-110', 'OpenAPS should have a fixed spot to check for and implement updates in every (~5 minute) OpenAPS loop'),
Does "updates" mean new settings here? Or real software updates?

2023-11-23 15:13 UTC, nicpappler commented on applying-stpa/l2_reqs.txt
> + ('REQ-136', 'Algorithm must use OpenAPS commands in the correct context'),
Do we need to specify the context in more detail? I'm lost what is meant here with context.

2023-11-23 19:16 UTC, milanlakhani commented
@abdik-tech @kestewart We are missing signoffs on Abdi commits here

2023-11-24 14:46 UTC, abdik-tech commented
@milanlakhani @kestewart My Sincerest apologies. Just discovered that I had to make the changes on my past commits. Sign off 1 #24 & Sign off #23 are for "Sign-off-by:" correction.

2023-11-30 15:47 UTC, milanlakhani commented
Thanks @nicpappler for the comments, the spreadsheet problems have been resolved so I should be able to address your points in the following week!

2024-02-15 15:20 UTC, kestewart commented
Discussed with Milan, and he'll take a pass at the updates, then we'll merge.

2024-02-22 15:31 UTC, milanlakhani commented on applying-stpa/l2_reqs.txt
> + ('REQ-110', 'OpenAPS should have a fixed spot to check for and implement updates in every (~5 minute) OpenAPS loop'),
Could be either I suppose?

2024-04-04 14:24 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-2: If OpenAPS believes that data is too conflicting for a dosing recommendation to be made, OpenAPS should still predict the effect of the fallback dosing recommendation and if this is far out of
Updated conflicting to insufficient in spreadsheet

2024-04-11 13:43 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-66: - data on Nightscout has not been corrupted and has integrity checks
Update needed

2024-04-11 13:44 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-62: Validity of used glucose data from Nightscout must be checked. (Generally data coming from NightScout should maybe be checked?) Only valid data shall be used for the openAPS algorithms.
Update needed

2024-04-11 14:07 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-37: The insulin pump must be set to the correct time.
Make consistency between full stops or no full stop

2024-04-11 14:07 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-39: OpenAPS should be able to use human input glucose
Update: change use to register

2024-04-11 14:09 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-45: OpenAPS glucose level value must match glucose data from the CGM
Covered by REQ-43

2024-04-11 14:12 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-98: Compatible setups must be specified
This needs expanding, look in the spreadsheet for context

2024-04-11 14:13 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-102: OpenAPS should give a warninig if it is connected to incompatible devices or software versions in these devices
typo, 'warning'

2024-04-11 14:14 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-125: OpenAPS should give a warninig if it is connected to an incompatible version of NightScout
Typo, 'warning'

2024-04-11 14:15 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-126: "CGM clock must be accurate and match RasPi time and real clock time, to nearest X seconds
Unnecessary speech marks

2024-04-11 14:15 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-127: All times should be alligned with NTP or a common time source"
Speech marks, there might be a few cases of these

2024-04-11 14:16 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-140: - (expected behaviour)
Needs updating

2024-04-11 14:18 UTC, milanlakhani commented on applying-stpa/l1_reqs.txt
> +REQ-185: OpenAPS should follow good secure coding practices
Repeated

2024-04-11 14:20 UTC, milanlakhani commented on applying-stpa/l2_reqs.txt
> + ('REQ-38', "(I need help with this one!  It's not under OpenAPS's control)"),
Needs updating

2024-04-11 14:21 UTC, milanlakhani commented on applying-stpa/l2_reqs.txt
> + ('REQ-43', '(3) Alarm is needed if a handshake is expected but missing for too long (what is too long in this context?)'),
1-2-3 need removing

2024-04-11 14:21 UTC, milanlakhani commented on applying-stpa/l2_reqs.txt
> + ('REQ-54', '(2) There needs to be an external entity to monitor behaviour of RasPi OS'),
1-2-3 need removing

2024-04-11 14:21 UTC, milanlakhani commented on applying-stpa/l2_reqs.txt
> + ('REQ-108', '(4) Data faults that cannot be detected by OpenAPS must be avoided or mitigated by the other devices'),
1-2-3-4 need removing

2024-04-11 14:22 UTC, milanlakhani commented on applying-stpa/l2_reqs.txt
> + ('REQ-114', '(2) OpenAPS must have defined behaviour when timed-out data is detected'),
1-2 need removing

2024-04-11 14:23 UTC, milanlakhani commented on applying-stpa/l2_reqs.txt
> + ('REQ-124', 'Components must be connected to each other'),
Look for context and maybe expand

2024-10-24 14:17 UTC, closed without merging

2024-10-24 14:17 UTC, kestewart commented
Looks like the files are too outdated to review in this PR.   We're closing this one, and will start a new one, double checking for the comments that were made so far.